version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          no_output_timeout: 1h
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison
           git config --global user.name "Samyak"
           git config --global user.email "jainsamyak2002.sj@gmail.com"
           git config --global color.ui true
           ls
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
